/** This file is automatically generated by waterbird */
#ifndef WATERBIRD_WATERCONF_H
#define WATERBIRD_WATERCONF_H

#define WATERBIRD_VERSION_MAJOR 0
#define WATERBIRD_VERSION_MINOR 1
#define WATERBIRD_VERSION_PATCH 1
#define WATERBIRD_VERSION_EXTRA "dev"
#define WATERBIRD_VERSION_FULL  "0.1.1-dev"

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>

#include "./include/waterbird.h"
#include "./include/waterconf.h"

#endif
